spring.application.name=wallet-transfer


spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_db?TimeZone=UTC
spring.datasource.username=wallet_user
spring.datasource.password=wallet_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}