spring.application.name=wallet-transfer


spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_db?TimeZone=UTC
spring.datasource.username=wallet_user
spring.datasource.password=wallet_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


spring.flyway.url=jdbc:postgresql://localhost:5432/wallet_db
spring.flyway.user=wallet_user
spring.flyway.password=wallet_pass